spring:
  datasource:
    url: jdbc:mysql://localhost:3306/projecte_dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  error:
    include-message: always

logging:
  level:
    org.springframework.security: DEBUG

auth:
  max-devices: 2