spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console # ✅ Add explicit path to console

server:
  error:
    include-message: always

logging:
  level:
    org.springframework.security: DEBUG